ENH add random deviates
GalSim-developers/JAX-GalSim pull request #72
Opened 2023-10-08 20:50 UTC by beckermr

This PR adds random deviates. To be merged after #70

2023-10-11 13:20 UTC, beckermr commented
@ismael-mendoza This one is ready for review. It is a big one but it brings in a bunch of stuff that was missing and is needed to enable simulations directly on GPUs (eventually).

2023-10-12 00:05 UTC, ismael-mendoza commented
@beckermr thanks will take a look soon, apologies if I'm a bit slower this week due to the sprint week being next week

2023-10-17 17:55 UTC, ismael-mendoza requested changes
Looks good @beckermr - I have a couple of questions below.

2023-10-17 17:55 UTC, ismael-mendoza commented on tests/jax/galsim/test_random_jax.py
> +    # NOTE jax has a reliabble discard
```suggestion
    # NOTE jax has a reliable discard
```

2023-10-17 17:55 UTC, ismael-mendoza commented on tests/jax/galsim/test_random_jax.py
> +    # NOTE jax has a reliabble discard
```suggestion
    # NOTE jax has a reliable discard
```

2023-10-18 04:28 UTC, beckermr commented on tests/jax/galsim/test_wcs_jax.py
> -    world_origin = wcs.toWorld(wcs.origin)
yes not used.

2023-10-18 04:29 UTC, beckermr commented on jax_galsim/transform.py
> +            self._params["flux_ratio"] *= obj._params["flux_ratio"]
Yes it helps with jitting and makes the class have the same semantics as the other gsobjects.

2023-10-18 04:30 UTC, beckermr commented on jax_galsim/transform.py
> +        ky *= -1j * self.offset.y
There may be a small performance penalty for `.offset` but TBH I used whatever seemed clearer or matched the upstream galsim code better.

2023-10-18 04:31 UTC, beckermr commented on tests/jax/test_api.py
> +        if cls not in [jax_galsim.Convolution, jax_galsim.Deconvolution]:
The convolutions in jax-galsim do not support real-space. The previous PR wasn't running the tests and they did not pass before.

2023-10-18 04:32 UTC, beckermr commented on jax_galsim/random.py
> +        _initial_seed = seed or secrets.randbelow(2**31)
This ensures we follow the galsim API. Here is the relevant text

> A seed of 0 or None means to pick some arbitrary value that will be different each time you run the program.

See https://galsim-developers.github.io/GalSim/_build/html/deviate.html#galsim.BaseDeviate.

2023-10-18 04:33 UTC, beckermr commented on jax_galsim/core/utils.py
> +            return x[0].astype(float).item()
This function is meant to convert scalars only and so we take only the zeroth element.

2023-10-18 04:35 UTC, beckermr commented on .pre-commit-config.yaml
> +        exclude: tests/GalSim/|tests/Coord/|tests/jax/galsim/
The files in that directory are hacked up files copied out of galsim. If we enforced out linting conventions, it'd make the source look a lot different than the galsim source. It is more useful to have the source be close to the galsim source so we can understand differences.

2023-10-18 11:46 UTC, beckermr commented on jax_galsim/transform.py
> +        return self._params["offset"]
removed!

2023-10-18 11:48 UTC, beckermr commented
ok @ismael-mendoza this is ready to merge!

2023-10-18 12:24 UTC, ismael-mendoza approved these changes
Looks good!

2023-10-18 13:06 UTC, merged