Updated to latest JAX version and pin
GalSim-developers/JAX-GalSim pull request #94
Opened 2024-06-03 17:11 UTC by ismael-mendoza

I was thinking it would be good to update to the latest jax version and pin `jax-galsim` to that if possible. Open to discussion on this though.

Changes: 
- `_wraps` to `implements` (still won't work for `galsim` but allows code to run, see #93 )

2024-06-03 18:36 UTC, beckermr requested changes
Please do not pin deps. It just puts off the pain of figuring things out and causes issues downstream. Let's go digging and figure out what tensorflow-probability did with the special functions we need from them.

2024-06-03 18:54 UTC, beckermr commented
tfp changed their default submodule imports. A direct import of the bessel function we need works fine.

2024-06-04 18:12 UTC, beckermr commented
Nest issue here is that pytest version 8 broke the test mangling we do on galsim. I am looking into that now.

2024-06-05 01:45 UTC, beckermr commented on tests/jax/test_api.py
> +    "'jaxlib.xla_extension.ArrayImpl' object has no attribute 'lower'",
```suggestion
    "object has no attribute 'lower'",
```

2024-06-05 02:23 UTC, beckermr approved these changes

2024-06-05 02:25 UTC, beckermr commented
This PR is ready to go. No API changes here, just updates to the tests etc. Shall we merge @ismael-mendoza?

2024-06-05 02:26 UTC, beckermr commented
Also, we should squash when merging. The commit history here is a disaster.

2024-06-05 12:23 UTC, ismael-mendoza commented
yes I think so! thank you! 

I agree with the squash and merge, I removed the other options from the settings

2024-06-05 12:24 UTC, beckermr commented
Ahhhhh we should keep the other options in the settings IMHO. I simply meant for this PR we'd squash.

2024-06-05 12:24 UTC, merged